version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    networks:
      - lab2
    restart: always
    volumes:
      - mongodb_data_container:/data/db

  node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 3333:3000
    depends_on:
      - mongodb
    networks:
      - lab2
    restart: always

networks:
  lab2:

volumes:
  mongodb_data_container:
